kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang:1.18
    commands:
      - make install

  - name: test
    image: golang:1.18
    commands:
      - make test-coverage

  - name: linter
    image: golangci/golangci-lint:latest
    commands:
      - make linter

  - name: build
    image: golang:1.18
    commands:
      - make build